# Generated by Django 4.2.3 on 2023-08-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('napp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='joiningdate',
            field=models.DateField(null=True),
        ),
    ]
